services:
  - type: web
    name: orcax-notice-backend-5000
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/noticeDB
